## Álgebra Lineal Computacional - 2C 2022

# Librería Numpy

### Arrays

En ALC vamos a trabajar sobre todo con _**arrays**_ que nos van a servir para representar vectores o matrices. Para crear arrays es necesario utilizar el módulo **numpy**


In [2]:
import numpy as np #importa el módulo numpy, con el alias np
v  = np.array([1,0,-1]) #genera un array v, con los elementos 1,0 y -1.
print(v)

[ 1  0 -1]


$v$ parece una lista, pero en realidad es un array creado a partir de una lista. Esto permite realizar distintas operaciones. Por ejemplo:

In [3]:
u  = np.array([3,1,2])
w1 = u+v #suma casillero a casillero
w2 = u*v #multiplica casillero a casillero
w3 = u@v #realiza el producto interno o escalar
print('w1 =',w1)
print('w2 =',w2)
print('w3 =',w3)

w1 = [4 1 1]
w2 = [ 3  0 -2]
w3 = 1


De manera similar se pueden crear matrices, observen que se lista de a filas:

In [4]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


Para conocer la forma de un array, se puede usar el comando $shape$:

In [5]:
print(A.shape)

(2, 3)


### Tuplas
El comando $shape$ devuelve una **tupla**. Una tupla es similar a una lista: puede contener varios valores, ordenados, y se puede acceder a ellos usando corchetes e índices. Una tupla va encerrada entre paréntesis. Sus elementos no se pueden modificar individualmente.

De este modo: A.shape[0] devuelve el número de filas, y A.shape[1] el número de columnas.

In [6]:
print(A.shape[0])
print(A.shape[1])

2
3


De manera similar:

In [7]:
tam = A.shape
print('Tam:',tam)
print('#filas:',tam[0])
print('#cols:',tam[1])

Tam: (2, 3)
#filas: 2
#cols: 3


### Ejercicio:
Definir las siguientes matrices y realizar, de ser posible, las operaciones indicadas:
$$A = \begin{pmatrix} 3 & 2 & 2 \\ -1 & 0 & 1 \\ -2 & 2 & 4 \end{pmatrix} \quad 
B=\begin{pmatrix} 0 & 1 & -1 \\ 5 & -2 & 1 \end{pmatrix} \quad v = (-1, 2, 1)$$
Calcular $A.v$ y $B.A$ ¿Qué tamaño tiene B.A?

In [11]:
A=#completar
B=#completar
v=#completar
print()#Ojo con la notación! No usar * para el producto! Se puede usar @ o bien np.dot
print()
print("el tamaño de B.A es:", #completar)

SyntaxError: invalid syntax (<ipython-input-11-286ce048f174>, line 1)

## Sistemas de ecuaciones lineales

Para resolver el sistema de ecuaciones lineales $Ax=b$ utilizamos ``np.linalg.solve(A,b)``. ¡OJO! $A$ debe ser una matriz cuadrada.

In [9]:
np.linalg.solve(A, v)

LinAlgError: Last 2 dimensions of the array must be square

### La función ``row_echelon`` para escalonar matrices.
El archivo **row_echelon.py** contiene la función *row_echelon*, que realiza la triangulación de una matriz. El comando %run ejecuta el archivo, de modo que la función está disponible para usar. Es equivalente a copiar y pegar el contenido del archivo dentro de una celda de código.

In [ ]:
from row_echelon import * #esto importa el contenido del paquete row_echelon: no hace falta usar prefijo. 

Por ejemplo, para resolver el sistema homogéneo:
$\left\{
\begin{array}{lcc}
     x_1-2x_2+x_3 & = & 0
  \\ 2x_1+x_2-x_3+x_4 & = & 0
  \\ 5x_2-3x_3+2x_4 & = & 0
\end{array}
\right.$

Ingresamos la matriz de coeficientes asociada al sistema y la escalonamos:

In [ ]:
A = np.array([[1,-2,1,0],[2,1,-1,1],[0,5,-3,2]])
print(A)
C = row_echelon(A)
print(C)

¿Cuál es el rango de $A$? ¿Cómo se clasifica el sistema?

#### Ejemplo con complejos:
Ingresemos una matriz con números complejos y escalonémosla. Tener en cuenta que el número $2-i$ se escribe $2-1j$:

In [ ]:
A = np.array([[1+1j,2,-2,1+1j],[1j,1-1j,-1,1+1j],[2,2,-1j,3-2j]])
B = row_echelon(A) 
print(B)

## Ejercicio:
Ingresen las matrices asociadas a los sistemas vistos en clase y escalonen para corroborar resultados. Utilizamos $np.c\_ [A,b]$ para formar la matriz ampliada $(A|b)$:

In [12]:
A= #completar
b= #completar
Ab= #armar la matriz ampliada asociada al sistema
print()
B= #escalonar
print()

SyntaxError: invalid syntax (<ipython-input-12-97d4432ad29e>, line 1)