In [18]:
import numpy as np

#1)
#a)
v1 = np.array([[1, 1, -2, 1], [3, -2, 1, 5], [1, -1, 1, 2], [1, -1, 1, 6]])
print(v1)
v2 = np.array([-2, 3, 2, 7])
np.linalg.solve(v1, v2)

[[ 1  1 -2  1]
 [ 3 -2  1  5]
 [ 1 -1  1  2]
 [ 1 -1  1  6]]


array([-1.5 , -0.25,  0.75,  1.25])